### ISSUE TITLE
Wildcard subdomains & Certbot 0.22.0

### ISSUE THREAD

**Issue by sebastianKline** [NVISIA/certbot-route53#4]
Please re-build and push this image so we can get the latest certbot, which now supports wildcard subdomains. 

@scottconnerly

**Comment by mpanthofer** [comment]
@scottconnerly, the image is rebuilding on on Docker Hub. I did manually build and push: ntcnvisia/certbot-route53:18-10-2 as well.  Please check it out.

**Comment by scottconnerly** [comment]
We may need to re-re-build after PR #6
